x-silo-env: &silo-env
  environment:
    - PORT=3000
    - BATCH_SIZE=${BATCH_SIZE:-60}
    - MQ_PREFETCH_COUNT=${MQ_PREFETCH_COUNT:-5}
    - APP_BASE_URL=${APP_BASE_URL:-http://web:3000}
    - SILO_API_BASE_URL=${SILO_API_BASE_URL:-http://localhost:5050}
    - DB_URL=${DB_URL:-postgresql://plane:plane@plane-db/silo}
    - AMQP_URL=${AMQP_URL:-amqp://guest:guest@plane-mq:5672/}
    - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379/}
    - SENTRY_DSN=${SENTRY_DSN:-" "}
    - JIRA_CLIENT_ID=${JIRA_CLIENT_ID:-""}
    - JIRA_CLIENT_SECRET=${JIRA_CLIENT_SECRET:-""}
    - LINEAR_CLIENT_ID=${LINEAR_CLIENT_ID:-""}
    - LINEAR_CLIENT_SECRET=${LINEAR_CLIENT_SECRET:-""}

x-monitor-env: &monitor-env
  environment:
    - SERVICE_HTTP_WEB=web:3000
    - SERVICE_HTTP_API=api:8000
    - SERVICE_HTTP_LIVE=live:3000
    - SERVICE_HTTP_PROXY=proxy:80
    - SERVICE_HTTP_MINIO=plane-minio:9090
    - SERVICE_TCP_REDIS=plane-redis:6379
    - SERVICE_TCP_POSTGRES=plane-db:5432
    - TRUSTED_PROXIES=${TRUSTED_PROXIES:-0.0.0.0/0}

x-proxy-env: &proxy-env
  environment:
    - SITE_ADDRESS=${SITE_ADDRESS:-localhost:80}
    - CERT_EMAIL=${CERT_EMAIL:-admin@example.com}
    - CERT_ACME_CA=${CERT_ACME_CA:-}
    - CERT_ACME_DNS=${CERT_ACME_DNS:-}
    - BUCKET_NAME=${BUCKET_NAME:-uploads}
    - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
    - LISTEN_HTTP_PORT=${LISTEN_HTTP_PORT:-80}
    - LISTEN_HTTPS_PORT=${LISTEN_HTTPS_PORT:-443}

x-app-env: &app-env
  environment:
    - WEB_URL=${WEB_URL:-http://localhost}
    - DEBUG=${DEBUG:-0}
    - SENTRY_DSN=${SENTRY_DSN:-""}
    - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-"production"}
    - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
    - API_BASE_URL=${API_BASE_URL:-http://api:8000}
    # Gunicorn Workers
    - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
    #DB SETTINGS
    - PGHOST=${PGHOST:-plane-db}
    - PGDATABASE=${PGDATABASE:-plane}
    - POSTGRES_USER=${POSTGRES_USER:-plane}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-plane}
    - POSTGRES_DB=${POSTGRES_DB:-plane}
    - PGDATA=${PGDATA:-/var/lib/postgresql/data}
    - SILO_DB=${SILO_DB:-silo}
    - DATABASE_URL=${DATABASE_URL:-postgresql://plane:plane@plane-db/plane}
    # REDIS SETTINGS
    - REDIS_HOST=${REDIS_HOST:-plane-redis}
    - REDIS_PORT=${REDIS_PORT:-6379}
    - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379/}
    # RabbitMQ Settings
    - RABBITMQ_HOST=${RABBITMQ_HOST:-plane-mq}
    - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-plane}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-plane}
    - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-plane}
    - RABBITMQ_VHOST=${RABBITMQ_VHOST:-plane}
    - AMQP_URL=${AMQP_URL:-amqp://plane:plane@plane-mq:5672/plane}
    # Application secret
    - SECRET_KEY=${SECRET_KEY:-60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5}
    # DATA STORE SETTINGS
    - USE_MINIO=${USE_MINIO:-1}
    - AWS_REGION=${AWS_REGION:-}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-"access-key"}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-"secret-key"}
    - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL:-http://plane-minio:9000}
    - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-uploads}
    - MINIO_ROOT_USER=${MINIO_ROOT_USER:-"access-key"}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-"secret-key"}
    - BUCKET_NAME=${BUCKET_NAME:-uploads}
    - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
    - SSL_VERIFY=${SSL_VERIFY:-1}
    - FEATURE_FLAG_SERVER_BASE_URL=${FEATURE_FLAG_SERVER_BASE_URL:-http://monitor:8080}
    - PAYMENT_SERVER_BASE_URL=${PAYMENT_SERVER_BASE_URL:-http://monitor:8080}

x-live-env: &live-env
  environment:
    - API_BASE_URL=${API_BASE_URL:-http://api:8000}
    - REDIS_HOST=${REDIS_HOST:-plane-redis}
    - REDIS_PORT=${REDIS_PORT:-6379}
    - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379/}

services:
  admin:
    <<: *app-env
    image: registry.plane.tools/plane/admin-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node admin/server.js admin
    deploy:
      replicas: ${ADMIN_REPLICAS:-1}
    depends_on:
      - api
      - web

  silo:
    <<: *silo-env
    image: registry.plane.tools/plane/silo-enterprise:${APP_RELEASE_VERSION}
    restart: always
    command: node silo/start.js
    depends_on:
      plane-mq:
        condition: service_healthy
      silo_migrator:
        condition: service_completed_successfully

  silo_migrator:
    <<: *silo-env
    image: registry.plane.tools/plane/silo-enterprise:${APP_RELEASE_VERSION}
    restart: "no"
    command: npm --prefix ./silo run db:migrate
    depends_on:
      plane-db:
        condition: service_healthy
      plane-mq:
        condition: service_healthy

  web:
    <<: *app-env
    image: registry.plane.tools/plane/web-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node web/server.js web
    deploy:
      replicas: ${WEB_REPLICAS:-1}
    depends_on:
      - api
      - worker

  space:
    <<: *app-env
    image: registry.plane.tools/plane/space-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node space/server.js space
    deploy:
      replicas: ${SPACE_REPLICAS:-1}
    depends_on:
      - api
      - web

  live:
    <<: *live-env
    image: registry.plane.tools/plane/live-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node live/dist/server.js live
    deploy:
      replicas: ${LIVE_REPLICAS:-1}
    depends_on:
      - api
      - web

  monitor:
    <<: *monitor-env
    image: registry.plane.tools/plane/monitor-enterprise:${APP_RELEASE_VERSION}
    restart: on-failure:5
    volumes:
      - ${INSTALL_DIR}/data/monitor:/app

  api:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-api-ee.sh
    deploy:
      replicas: ${API_REPLICAS:-1}
    volumes:
      - ${INSTALL_DIR}/logs/api:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis

  worker:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-worker.sh
    volumes:
      - ${INSTALL_DIR}/logs/worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-beat.sh
    volumes:
      - ${INSTALL_DIR}/logs/beat-worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: "no"
    command: ./bin/docker-entrypoint-migrator.sh
    volumes:
      - ${INSTALL_DIR}/logs/migrator:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis

  plane-db:
    <<: *app-env
    image: registry.plane.tools/plane/postgres:15.5-alpine
    restart: unless-stopped
    command: >
      bash -c '
        docker-entrypoint.sh postgres &
        sleep 5 &&
        result=$(PGPASSWORD=${POSTGRES_PASSWORD} psql -U $POSTGRES_USER -tAc "SELECT 1 FROM pg_database WHERE datname='${SILO_DB}'") &&
        echo "$result" | grep -q 1 && result=0 || result=1 &&
        if [ $result -eq 0 ]; then
          echo "Database '${SILO_DB}' already exists"
        else
          PGPASSWORD=${POSTGRES_PASSWORD} psql -U $POSTGRES_USER -c "CREATE DATABASE ${SILO_DB};"
          echo "Created database '${SILO_DB}'"
        fi &&
        wait
      '
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'PGPASSWORD=${POSTGRES_PASSWORD} psql -U $POSTGRES_USER -tAc "SELECT CASE WHEN EXISTS(SELECT 1 FROM pg_database WHERE datname=''${SILO_DB}'') THEN 1 ELSE 0 END AS ${SILO_DB}, CASE WHEN EXISTS(SELECT 1 FROM pg_database WHERE datname=''${POSTGRES_DB}'') THEN 1 ELSE 0 END AS ${POSTGRES_DB}" | grep -q ''1|1'' && echo ''Both databases exist'' || (echo ''One or both databases are missing'' && exit 1)',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    # volumes:
    #   - ${INSTALL_DIR}/data/db:/var/lib/postgresql/data

  plane-redis:
    <<: *app-env
    image: registry.plane.tools/plane/valkey:7.2.5-alpine
    restart: unless-stopped
    volumes:
      - ${INSTALL_DIR}/data/redis:/data

  plane-mq:
    <<: *app-env
    image: registry.plane.tools/plane/rabbitmq:3.13.6-management-alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ${INSTALL_DIR}/data/mq:/var/lib/rabbitmq

  plane-minio:
    <<: *app-env
    image: registry.plane.tools/plane/minio:latest
    restart: unless-stopped
    command: server /export --console-address ":9090"
    volumes:
      - ${INSTALL_DIR}/data/minio/uploads:/export
      - ${INSTALL_DIR}/data/minio/data:/data

  # Comment this if you already have a reverse proxy running
  proxy:
    <<: *proxy-env
    image: registry.plane.tools/plane/caddy:latest
    restart: unless-stopped
    ports:
      - ${LISTEN_HTTP_PORT:-80}:${LISTEN_HTTP_PORT:-80}
      - ${LISTEN_HTTPS_PORT:-443}:${LISTEN_HTTPS_PORT:-443}
    volumes:
      - ${INSTALL_DIR}/Caddyfile:/etc/caddy/Caddyfile
      - ${INSTALL_DIR}/caddy/config:/config
      - ${INSTALL_DIR}/caddy/data:/data
    depends_on:
      - web
      - api
      - space
      - admin
      - live
