name: Create PR on Sync

on:
  workflow_dispatch:
  push:
    branches:
      - "sync/**"

env:
  CURRENT_BRANCH: ${{ github.ref_name }}
  SOURCE_BRANCH: ${{ vars.SYNC_SOURCE_BRANCH_NAME }} # The sync branch such as "sync/ce"
  TARGET_BRANCH: ${{ vars.SYNC_TARGET_BRANCH_NAME }} # The target branch that you would like to merge changes like develop
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Personal access token required to modify contents and workflows
  REVIEWER: ${{ vars.SYNC_PR_REVIEWER }}
  ACCOUNT_USER_NAME: ${{ vars.ACCOUNT_USER_NAME }}
  ACCOUNT_USER_EMAIL: ${{ vars.ACCOUNT_USER_EMAIL }}

jobs:
  Check_Branch:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_MATCH: ${{ steps.check-branch.outputs.MATCH }}
    steps:
      - name: Check if current branch matches the secret
        id: check-branch
        run: |
          if [ "$CURRENT_BRANCH" = "$SOURCE_BRANCH" ]; then
            echo "MATCH=true" >> $GITHUB_OUTPUT
          else
            echo "MATCH=false" >> $GITHUB_OUTPUT
          fi
  Auto_Merge:
    if: ${{ needs.Check_Branch.outputs.BRANCH_MATCH == 'true' }}
    needs: [Check_Branch]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Git
        run: |
          git config user.name "$ACCOUNT_USER_NAME"
          git config user.email "$ACCOUNT_USER_EMAIL"

      - name: Setup GH CLI and Git Config
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Create PR to Target Branch
        run: |
          # get all pull requests and check if there is already a PR
          PR_EXISTS=$(gh pr list --base $TARGET_BRANCH --head $SOURCE_BRANCH --state open --json number | jq '.[] | .number')
          if [ -n "$PR_EXISTS" ]; then
            echo "Pull Request already exists: $PR_EXISTS"
          else
            echo "Creating new pull request"
            PR_URL=$(gh pr create --base $TARGET_BRANCH --head $SOURCE_BRANCH --title "sync: community changes" --body "")
            echo "Pull Request created: $PR_URL"
          fi
