name: Create PR in Plane EE Repository to sync the changes

on:
  pull_request:
    types:
      - closed

jobs:
  create_pr:
    # Only run the job when a PR is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Set up Branch Name
        run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          
      - name: Setup GH CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Create Pull Request
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            TARGET_REPO="makeplane/${{ secrets.REPO_NAME }}"
            TARGET_BRANCH="${{ secrets.REPO_TARGET_BRANCH }}"
            SOURCE_BRANCH="${{ env.BRANCH_NAME }}"
            
            git checkout $SOURCE_BRANCH
            git remote add target "https://$GH_TOKEN@github.com/$TARGET_REPO.git"
            git push target $SOURCE_BRANCH:$SOURCE_BRANCH

            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_BODY="${{ github.event.pull_request.body }}"
            
            gh pr create \
              --base $TARGET_BRANCH \
              --head $SOURCE_BRANCH \
              --title "$PR_TITLE" \
              --body "$PR_BODY" \
              --repo $TARGET_REPO
  
